## TENSOR(텐서)
: 배열이나 행렬과 매우 유사한 특수한 자료구조

---
* PyTorch에서는 텐서를 사용하여 모델의 입력과 출력, 그리고 모델의 매개변수들을 부호화(encode)한다. 

* GPU나 다른 하드웨어 가속기에서 실행할 수 있다는 점만 제외하면 NumPy의 ndarray와 유사하다. 

* 텐서와 NumPy 배열(array)은 종종 동일한 내부(underly) 메모리를 공유할 수 있어 데이터를 복사할 필요가 없다.

* 텐서는 자동 미분(automatic differentiation)에 최적화되어 있다. 

In [1]:
import torch
import numpy as np

# 텐서 초기화
1. 데이터로부터 직접 생성하기
2. NumPy 배열로부터 생성하기
3. 다른 텐서로부터 생성하기 
4. 무작위(random) 또는 상수(constant) 값을 사용하기

In [3]:
# 1. 데이터로부터 직접 생성하기
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [4]:
# 2. NumPy 배열로부터 생성하기
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [6]:
# 3. 다른 텐서로부터 생성하기 
# 3-1. 명시적으로 재정의(override)하지 않는다면, 인자로 주어진 텐서의 속성(모양(shape), 자료형(datatype)을 유지한다. 
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지한다.
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어쓴다.
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7332, 0.9773],
        [0.7500, 0.8972]]) 



In [7]:
# 4. 무작위(random) 또는 상수(constant) 값을 사용하기
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6403, 0.7629, 0.1335],
        [0.1459, 0.0963, 0.1769]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### 텐서의 속성(Attribute)
: 텐서의 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지를 나타낸다. 

In [8]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### 텐서 연산(Operation)
: 전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 임의 샘플링(random sampling) 등 

- 각 연산들은 GPU에서 실행 가능하다. 
- 기본적으로 텐서는 CPU에 생성된다. (메소드 사용 시 GPU로 명시적 이동 가능)
- 장치들 간 큰 텐서를 복사하는 것은 시간과 메모리 측면에서 비용이 많이 든다!

In [9]:
# GPU가 존재하면 텐서를 이동
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [10]:
# NumPy식의 표준 인덱싱과 슬라이싱
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [11]:
# 텐서 합치기
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [12]:
# 산술 연산(Arithmetic operations)

# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산. y1, y2, y3은 모두 같은 값을 갖는다.
# ``tensor.T`` 는 텐서의 전치(transpose)를 반환.
y1 = tensor @ tensor.T # @ : 행렬 곱셈
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# 요소별 곱(element-wise product)을 계산. z1, z2, z3는 모두 같은 값을 갖는다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [13]:
# 단일 요소(single-element)텐서
# : 텐서의 모든 값을 하나로 집계하여 요소가 하나인 텐서의 경우, item()을 사용하여 Python 숫자 값으로 변환할 수 있다. 
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [14]:
# 바꿔치기(in-place) 연산
# : 연산 결과를 피연산자(operand)에 저장하는 연산, 접미사를 갖는다. 
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

# 바뀌치기 연산은 메모리를 일부 절약하지만, (사용 권장 X)
# 기록이 즉시 삭제되어 도함수(derivative) 계산에 문제가 발생할 수 있다. 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


### NumPy 변환(Bridge)
: CPU 상의 텐서와 NumPy 배열은 메모리 공간을 공유하므로, 하나를 변경하면 다른 하나도 변경된다. 

In [15]:
# 텐서를 NumPy 배열로 변환하기
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [16]:
# 텐서의 변경 사항이 NumPy 배열에 반영된다. 
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [18]:
# NumPy 배열을 텐서로 변환하기
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
